[package]
name = "ci_r"
version = "0.1.0"
edition = "2021"
authors = ["Your Team <team@example.com>"]
license = ""
description = "extendr bindings for Conditional Independence Testing"
repository = ""

[dependencies]
ci_core = { path = "../ci-core" }
anyhow = { workspace = true}
extendr-api = { version = "0.9.0", features = ["ndarray"] }

[lints]
workspace = true

[lib]
