# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib cir, .registration = TRUE
NULL

RChiSquared <- new.env(parent = emptyenv())

RChiSquared$new <- function(boolean, significance_level) .Call(wrap__RChiSquared__new, boolean, significance_level)

RChiSquared$run_test <- function(x_values, y_values, z) .Call(wrap__RChiSquared__run_test, self, x_values, y_values, z)

#' @export
`$.RChiSquared` <- function (self, name) { func <- RChiSquared[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RChiSquared` <- `$.RChiSquared`

RLogLikelihood <- new.env(parent = emptyenv())

RLogLikelihood$new <- function(boolean, significance_level) .Call(wrap__RLogLikelihood__new, boolean, significance_level)

RLogLikelihood$run_test <- function(x_values, y_values, z) .Call(wrap__RLogLikelihood__run_test, self, x_values, y_values, z)

#' @export
`$.RLogLikelihood` <- function (self, name) { func <- RLogLikelihood[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RLogLikelihood` <- `$.RLogLikelihood`

RCressieRead <- new.env(parent = emptyenv())

RCressieRead$new <- function(boolean, significance_level) .Call(wrap__RCressieRead__new, boolean, significance_level)

RCressieRead$run_test <- function(x_values, y_values, z) .Call(wrap__RCressieRead__run_test, self, x_values, y_values, z)

#' @export
`$.RCressieRead` <- function (self, name) { func <- RCressieRead[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RCressieRead` <- `$.RCressieRead`

RPearsonCorrelation <- new.env(parent = emptyenv())

RPearsonCorrelation$new <- function(boolean, significance_level) .Call(wrap__RPearsonCorrelation__new, boolean, significance_level)

RPearsonCorrelation$run_test <- function(x_values, y_values, z) .Call(wrap__RPearsonCorrelation__run_test, self, x_values, y_values, z)

#' @export
`$.RPearsonCorrelation` <- function (self, name) { func <- RPearsonCorrelation[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RPearsonCorrelation` <- `$.RPearsonCorrelation`

RFreemanTukey <- new.env(parent = emptyenv())

RFreemanTukey$new <- function(boolean, significance_level) .Call(wrap__RFreemanTukey__new, boolean, significance_level)

RFreemanTukey$run_test <- function(x_values, y_values, z) .Call(wrap__RFreemanTukey__run_test, self, x_values, y_values, z)

#' @export
`$.RFreemanTukey` <- function (self, name) { func <- RFreemanTukey[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RFreemanTukey` <- `$.RFreemanTukey`

RModifiedLikelihood <- new.env(parent = emptyenv())

RModifiedLikelihood$new <- function(boolean, significance_level) .Call(wrap__RModifiedLikelihood__new, boolean, significance_level)

RModifiedLikelihood$run_test <- function(x_values, y_values, z) .Call(wrap__RModifiedLikelihood__run_test, self, x_values, y_values, z)

#' @export
`$.RModifiedLikelihood` <- function (self, name) { func <- RModifiedLikelihood[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RModifiedLikelihood` <- `$.RModifiedLikelihood`

RPearsonEquivalence <- new.env(parent = emptyenv())

RPearsonEquivalence$new <- function(boolean, significance_level) .Call(wrap__RPearsonEquivalence__new, boolean, significance_level)

RPearsonEquivalence$run_test <- function(x_values, y_values, z) .Call(wrap__RPearsonEquivalence__run_test, self, x_values, y_values, z)

#' @export
`$.RPearsonEquivalence` <- function (self, name) { func <- RPearsonEquivalence[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RPearsonEquivalence` <- `$.RPearsonEquivalence`

# nolint end
