[package]
name = "ci_python"
version = "0.1.0"
edition = "2021"
authors = ["Your Team <team@example.com>"]
license = ""
description = "PyO3 bindings for Conditional Independence Testing"
repository = ""

[dependencies]
ci-core = { path = "../ci-core" }
ndarray = { workspace = true }
numpy = "0.28.0"
pyo3 = { workspace = true }

[lints]
workspace = true

[lib]
name = "_ci_python"
crate-type = ["cdylib"]
