[package]
name = "ci-core"
version = "0.1.0"
edition = "2021"
authors = ["Your Team <team@example.com>"]
license = ""
description = "Conditional Independence Testing"
repository = ""
keywords = ["statistics", "causal-inference", "conditional-independence"]
categories = ["science"]

exclude = [""]

[dependencies]
anyhow = { workspace = true}
serde = { workspace = true }
thiserror = { workspace = true }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
statrs = { workspace = true }
scirs2-core = { workspace = true }
scirs2-linalg = { workspace = true }
scirs2-stats = { workspace = true }
scirs2 = { workspace = true }
rand = "0.10.0"
scirs2-neural = "0.2.0"
lapack = "0.19"

[target.'cfg(unix)'.dependencies]
lapack-src = { version = "0.10", features = ["openblas"] }

[target.'cfg(windows)'.dependencies]
lapack-src = { version = "0.10", features = ["intel-mkl"] }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true

[lib]
