# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "CITest",
    "Registry",
]

@typing.final
class CITest:
    def __call__(self, z: numpy.typing.NDArray[numpy.float64], x: numpy.typing.NDArray[numpy.float64], y: numpy.typing.NDArray[numpy.float64]) -> typing.Any:
        r"""
        Run the conditional independence test on the given data.
        
        # Errors
        
        Returns `PyRuntimeError` if the test lookup fails or the test itself returns an error.
        """

@typing.final
class Registry:
    def __new__(cls) -> Registry: ...
    def list_all_tests(self) -> builtins.list[builtins.str]: ...
    def get_test(self, test_name: builtins.str) -> CITest: ...

